name: Publish packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk14:alpine-slim
    steps:
      - name: Install git
        run: apk add --no-cache git
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
